version = "1"

[hooks]
# Define the pre-commit hook
pre-commit = "cargo fmt -- --check"

# Define the pre-push hook
pre-push = "cargo test"

# Define the commit-msg hook
commit-msg = "validate-commit-msg"

# Define the post-checkout hook
post-checkout = "echo 'Checked out to a new branch'"

[logging]
verbose = true
